### ISSUE TITLE
feature request: add non standard `address` field to `EthKeyStore`

### ISSUE THREAD

**Issue by tynes** [roynalnaruto/eth-keystore-rs#11]
While it is not defined as part of the spec and could be interpreted as bad for privacy, `geth` serializes the address that corresponds to the key as part of the keystore JSON. What do you think about adding an `Option<[u8; 20]>` or `Option<String>` that represents the address field to the `EthKeyStore`?

Example of a key created by geth:
```json
{
  "address": "00000398232e2064f896018496b4b44b3d62751f",
  "crypto": {
    "cipher": "aes-128-ctr",
    "ciphertext": "4f784cd629a7caf34b488e36fb96aad8a8f943a6ce31c7deab950c5e3a5b1c43",
    "cipherparams": {
      "iv": "76f07196b3c94f25b8f34d869493f640"
    },
    "kdf": "scrypt",
    "kdfparams": {
      "dklen": 32,
      "n": 262144,
      "p": 1,
      "r": 8,
      "salt": "1e7be4ce8351dd1710b0885438414b1748a81f1af510eda11e4d1f99c8d43975"
    },
    "mac": "5b5433575a2418c1c813337a88b4099baa2f534e5dabeba86979d538c1f594d8"
  },
  "id": "6c4485f3-3cc0-4081-848e-8bf489f2c262",
  "version": 3
}
```

Relevant struct in `geth`: https://github.com/ethereum/go-ethereum/blob/fb3a6528cfa49f623570575c4fe9e8a716cfcdf7/accounts/keystore/key.go#L67

**Comment by roynalnaruto** [comment]
Hi @tynes Yes that's true `geth` does add an address field to the keystore, and after some conversations in the PR #8 I was requested by a user to not assume that this library will only be used for creating/encrypting/decrypting "Ethereum private keys" (@tmpfs was encrypting private key shares for an MPC construction).

But I do agree that compatibility with `geth` conventions might be a good-to-have for this repository.

How about I add a feature `geth-compat` and enable the `address` field when this feature is enabled? Would that be good for you @tynes ?

**Comment by tmpfs** [comment]
Ha, interesting that this come up. Rather than a `geth-compat` feature could we convert the extra argument to `Option<KeystoreOptions>` and then just do:

```rust
pub struct KeystoreOptions<'a> {
  /// File name, defaults to the UUID.
  pub name: Option<&'a str>,
  /// Public address, when available will be embedded in the keystore.
  pub address: Option<String>,
}
```

Does that work for you @roynalnaruto ?

**Comment by roynalnaruto** [comment]
From what I understood @tynes meant he would like support to read/write an `address` field in the JSON keystore. I think the best solution to enable that is by feature gating it as it depends on a few more dependencies which we wouldn't need if such support is not required (as in your case).

**Comment by roynalnaruto** [comment]
@tmpfs @tynes quick PR for this. Let me know if this is something you'd be okay with

**Comment by tynes** [comment]
> From what I understood @tynes meant he would like support to read/write an `address` field in the JSON keystore. I think the best solution to enable that is by feature gating it as it depends on a few more dependencies which we wouldn't need if such support is not required (as in your case).

This is definitely what I meant and I was concerned about adding new dependencies but putting it behind a feature gate solves that problem. Thank you!
