### ISSUE TITLE
the dependency of many crypto related crates are outdated.

### ISSUE THREAD

**Issue by guanqun** [roynalnaruto/eth-keystore-rs#3]
and their interfaces have changed a lot...

**Comment by roynalnaruto** [comment]
What version of `eth-keystore-rs` are you trying to use? The `master` branch compiles fine for me.

Could you specify which dependencies are outdated? I'll update them.

**Comment by roynalnaruto** [comment]
Merged #4 and published [v0.3.0](https://crates.io/crates/eth-keystore/0.3.0)

**Comment by guanqun** [comment]
thank you for the quick action!
