### ISSUE TITLE
Fine grained control of file names when writing keystore files

### ISSUE THREAD

**Issue by tmpfs** [roynalnaruto/eth-keystore-rs#7]
Currently files are written by convention using the UUID as the file name but I would prefer to follow the newer convention that `geth` uses which is UTC date concatenated with the public address of the key.

Also I have a use case for the keystore where I am storing other private secrets (for TOTP authentication) which I would like to write using a fixed file name, eg: `totp.json`.

If I do the work to allow callers to set the file name will you be willing to land the changes?

Thanks 🙏

**Comment by roynalnaruto** [comment]
We can change the default naming of the keystore file to the one followed by `geth`, and add an optional filename field to custom name the keystore file. Feel free to file a PR with these changes, otherwise I can do it when I find some time off :)

**Comment by tmpfs** [comment]
Great, thanks @roynalnaruto! I will put together a PR, I don't think we want to get involved with computing the public address and assuming an ECDSA private key as input so I think just passing in the `id` and using that as the file name works for all situations.

**Comment by tmpfs** [comment]
Closing now #9 has been merged, thanks @roynalnaruto!
